// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as GraphologySimplePath from "graphology-simple-path";

function MakeSimplePath(C) {
  return {
          allSimplePaths: (function (prim0, prim1, prim2, prim3, prim4) {
              return GraphologySimplePath.allSimplePaths(prim0, prim1, prim2, prim3 !== undefined ? Caml_option.valFromOption(prim3) : undefined);
            }),
          allSimpleEdgePaths: (function (prim0, prim1, prim2, prim3, prim4) {
              return GraphologySimplePath.allSimpleEdgePaths(prim0, prim1, prim2, prim3 !== undefined ? Caml_option.valFromOption(prim3) : undefined);
            }),
          allSimpleEdgeGroupPaths: (function (prim0, prim1, prim2, prim3, prim4) {
              return GraphologySimplePath.allSimpleEdgeGroupPaths(prim0, prim1, prim2, prim3 !== undefined ? Caml_option.valFromOption(prim3) : undefined);
            })
        };
}

export {
  MakeSimplePath ,
}
/* graphology-simple-path Not a pure module */
