// Generated by ReScript, PLEASE EDIT WITH CARE

import * as GraphologyTraversal from "graphology-traversal";

function MakeTraversal(C) {
  return {
    bfs: (prim0, prim1) => {
      GraphologyTraversal.bfs(prim0, prim1);
    },
    bfsFromNode: (prim0, prim1, prim2) => {
      GraphologyTraversal.bfsFromNode(prim0, prim1, prim2);
    },
    dfs: (prim0, prim1) => {
      GraphologyTraversal.dfs(prim0, prim1);
    },
    dfsFromNode: (prim0, prim1, prim2) => {
      GraphologyTraversal.dfsFromNode(prim0, prim1, prim2);
    }
  };
}

export {
  MakeTraversal,
}
/* graphology-traversal Not a pure module */
