// Generated by ReScript, PLEASE EDIT WITH CARE


function MakeNodesIter(C) {
  return {
    nodes: prim => prim.nodes(),
    forEachNode: (prim0, prim1) => {
      prim0.forEachNode(prim1);
    },
    mapNodes: (prim0, prim1) => prim0.mapNodes(prim1),
    filterNodes: (prim0, prim1) => prim0.filterNodes(prim1),
    reduceNodes: (prim0, prim1, prim2) => prim0.reduceNodes(prim1, prim2),
    findNode: (prim0, prim1) => prim0.findNode(prim1),
    someNode: (prim0, prim1) => prim0.someNode(prim1),
    everyNode: (prim0, prim1) => prim0.everyNode(prim1),
    nodeEntries: prim => prim.nodeEntries()
  };
}

export {
  MakeNodesIter,
}
/* No side effect */
