// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as GraphologyGexf from "graphology-gexf";

function MakeGEXF(C) {
  return {
          write: (function (prim0, prim1) {
              return GraphologyGexf.write(prim0, prim1 !== undefined ? Caml_option.valFromOption(prim1) : undefined);
            })
        };
}

export {
  MakeGEXF ,
}
/* graphology-gexf Not a pure module */
