// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as GraphologyLayout from "graphology-layout";

function MakeLayout(C) {
  return {
          circular: (function (prim0, prim1) {
              return GraphologyLayout.circular(prim0, prim1 !== undefined ? Caml_option.valFromOption(prim1) : undefined);
            }),
          Circular: {
            assign: (function (prim0, prim1) {
                GraphologyLayout.circular.assign(prim0, prim1 !== undefined ? Caml_option.valFromOption(prim1) : undefined);
              })
          }
        };
}

export {
  MakeLayout ,
}
/* graphology-layout Not a pure module */
