// Generated by ReScript, PLEASE EDIT WITH CARE

import GraphologySvg from "graphology-svg";
import * as Primitive_option from "rescript/lib/es6/Primitive_option.js";

function MakeSVG(C) {
  return {
    render: (prim0, prim1, prim2, prim3) => {
      GraphologySvg(prim0, prim1, prim2 !== undefined ? Primitive_option.valFromOption(prim2) : undefined, prim3);
    }
  };
}

export {
  MakeSVG,
}
/* graphology-svg Not a pure module */
