// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as GraphologyShortestPath from "graphology-shortest-path";

function MakeShortestPath(C) {
  return {
    Unweighted: {
      bidirectional: (prim0, prim1, prim2) => GraphologyShortestPath.unweighted.bidirectional(prim0, prim1, prim2),
      singleSource: (prim0, prim1) => GraphologyShortestPath.unweighted.singleSource(prim0, prim1),
      singleSourceLength: (prim0, prim1) => GraphologyShortestPath.unweighted.singleSourceLength(prim0, prim1),
      undirectedSingleSourceLength: (prim0, prim1) => GraphologyShortestPath.unweighted.undirectedSingleSourceLength(prim0, prim1)
    },
    Dijkstra: {
      bidirectional: (prim0, prim1, prim2, prim3) => GraphologyShortestPath.dijkstra.bidirectional(prim0, prim1, prim2, Primitive_option.unwrapPolyVar(prim3)),
      singleSource: (prim0, prim1, prim2) => GraphologyShortestPath.dijkstra.singleSource(prim0, prim1, Primitive_option.unwrapPolyVar(prim2))
    },
    AStar: {
      bidirectional: (prim0, prim1, prim2, prim3, prim4) => GraphologyShortestPath.astar.bidirectional(prim0, prim1, prim2, Primitive_option.unwrapPolyVar(prim3), prim4 !== undefined ? Primitive_option.valFromOption(prim4) : undefined)
    },
    Utils: {
      edgePathFromNodePath: (prim0, prim1) => GraphologyShortestPath.edgePathFromNodePath(prim0, prim1)
    }
  };
}

export {
  MakeShortestPath,
}
/* graphology-shortest-path Not a pure module */
