// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as GraphologyShortestPath from "graphology-shortest-path";

function MakeShortestPath(C) {
  return {
          Unweighted: {
            bidirectional: (function (prim0, prim1, prim2) {
                return GraphologyShortestPath.unweighted.bidirectional(prim0, prim1, prim2);
              }),
            singleSource: (function (prim0, prim1) {
                return GraphologyShortestPath.unweighted.singleSource(prim0, prim1);
              }),
            singleSourceLength: (function (prim0, prim1) {
                return GraphologyShortestPath.unweighted.singleSourceLength(prim0, prim1);
              }),
            undirectedSingleSourceLength: (function (prim0, prim1) {
                return GraphologyShortestPath.unweighted.undirectedSingleSourceLength(prim0, prim1);
              })
          },
          Dijkstra: {
            bidirectional: (function (prim0, prim1, prim2, prim3) {
                return GraphologyShortestPath.dijkstra.bidirectional(prim0, prim1, prim2, Caml_option.option_unwrap(prim3));
              }),
            singleSource: (function (prim0, prim1, prim2) {
                return GraphologyShortestPath.dijkstra.singleSource(prim0, prim1, Caml_option.option_unwrap(prim2));
              })
          },
          AStar: {
            bidirectional: (function (prim0, prim1, prim2, prim3, prim4) {
                return GraphologyShortestPath.astar.bidirectional(prim0, prim1, prim2, Caml_option.option_unwrap(prim3), prim4 !== undefined ? Caml_option.valFromOption(prim4) : undefined);
              })
          },
          Utils: {
            edgePathFromNodePath: (function (prim0, prim1) {
                return GraphologyShortestPath.edgePathFromNodePath(prim0, prim1);
              })
          }
        };
}

export {
  MakeShortestPath ,
}
/* graphology-shortest-path Not a pure module */
