// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "rescript/lib/es6/Primitive_option.js";
import * as GraphologyLayout from "graphology-layout";
import * as UtilsJs from "graphology-layout/utils.js";

function MakeLayout(C) {
  return {
    Circular: {
      circular: (prim0, prim1) => GraphologyLayout.circular(prim0, prim1 !== undefined ? Primitive_option.valFromOption(prim1) : undefined),
      assign: (prim0, prim1) => {
        GraphologyLayout.circular.assign(prim0, prim1 !== undefined ? Primitive_option.valFromOption(prim1) : undefined);
      }
    },
    Random: {
      random: (prim0, prim1) => GraphologyLayout.random(prim0, prim1 !== undefined ? Primitive_option.valFromOption(prim1) : undefined),
      assign: (prim0, prim1) => {
        GraphologyLayout.random.assign(prim0, prim1 !== undefined ? Primitive_option.valFromOption(prim1) : undefined);
      }
    },
    CirclePack: {
      circlePack: (prim0, prim1) => GraphologyLayout.circlepack(prim0, prim1 !== undefined ? Primitive_option.valFromOption(prim1) : undefined),
      assign: (prim0, prim1) => {
        GraphologyLayout.circlepack.assign(prim0, prim1 !== undefined ? Primitive_option.valFromOption(prim1) : undefined);
      }
    },
    Rotation: {
      rotation: (prim0, prim1, prim2) => GraphologyLayout.rotation(prim0, prim1, prim2 !== undefined ? Primitive_option.valFromOption(prim2) : undefined),
      assign: (prim0, prim1, prim2) => {
        GraphologyLayout.rotation.assign(prim0, prim1, prim2 !== undefined ? Primitive_option.valFromOption(prim2) : undefined);
      }
    },
    Utils: {
      collectLayout: (prim0, prim1) => UtilsJs.collectLayout(prim0, prim1 !== undefined ? Primitive_option.valFromOption(prim1) : undefined),
      collectLayoutAsFlatArray: (prim0, prim1) => UtilsJs.collectLayoutAsFlatArray(prim0, prim1 !== undefined ? Primitive_option.valFromOption(prim1) : undefined),
      assignLayout: (prim0, prim1, prim2) => {
        UtilsJs.assignLayout(prim0, prim1, prim2 !== undefined ? Primitive_option.valFromOption(prim2) : undefined);
      },
      assignLayoutAsFlatArray: (prim0, prim1, prim2) => UtilsJs.assignLayoutAsFlatArray(prim0, prim1, prim2 !== undefined ? Primitive_option.valFromOption(prim2) : undefined)
    }
  };
}

export {
  MakeLayout,
}
/* graphology-layout Not a pure module */
