// Generated by ReScript, PLEASE EDIT WITH CARE

import * as GraphologyGexf from "graphology-gexf";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function MakeGEXF(C) {
  return {
    write: (prim0, prim1) => GraphologyGexf.write(prim0, prim1 !== undefined ? Primitive_option.valFromOption(prim1) : undefined)
  };
}

export {
  MakeGEXF,
}
/* graphology-gexf Not a pure module */
