// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "rescript/lib/es6/Primitive_option.js";
import * as GraphologySimplePath from "graphology-simple-path";

function MakeSimplePath(C) {
  return {
    allSimplePaths: (prim0, prim1, prim2, prim3, prim4) => GraphologySimplePath.allSimplePaths(prim0, prim1, prim2, prim3 !== undefined ? Primitive_option.valFromOption(prim3) : undefined),
    allSimpleEdgePaths: (prim0, prim1, prim2, prim3, prim4) => GraphologySimplePath.allSimpleEdgePaths(prim0, prim1, prim2, prim3 !== undefined ? Primitive_option.valFromOption(prim3) : undefined),
    allSimpleEdgeGroupPaths: (prim0, prim1, prim2, prim3, prim4) => GraphologySimplePath.allSimpleEdgeGroupPaths(prim0, prim1, prim2, prim3 !== undefined ? Primitive_option.valFromOption(prim3) : undefined)
  };
}

export {
  MakeSimplePath,
}
/* graphology-simple-path Not a pure module */
