// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Graphology__Graph from "./Graphology__Graph.res.mjs";

function log(prim) {
  console.log(prim);
}

function log2(prim0, prim1) {
  console.log(prim0, prim1);
}

let H = Graphology__Graph.MakeGraph({});

let h = H.makeGraph(undefined);

H.addNode(h, "John", {
  lastName: "Doe",
  age: 30
});

H.addNode(h, "Peter", {
  lastName: "Choi",
  age: 21
});

H.addNode(h, "Mary", undefined);

H.addEdge(h, "John", "Peter", {
  dist: 23
});

H.addEdge(h, "Peter", "Mary", {
  dist: 12
});

let nodeIter = H.NodesIter.nodeEntries(h);

let nodeArr = Array.from(nodeIter);

console.log("arr", nodeArr);

let edgeIter = H.EdgesIter.directedEdgeEntries(h, {
  TAG: "Node",
  _0: "John"
});

let edgeArr = Array.from(edgeIter);

console.log("edgeArr", edgeArr);

export {
  log,
  log2,
  H,
  h,
  nodeIter,
  nodeArr,
  edgeIter,
  edgeArr,
}
/* H Not a pure module */
