// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/rescript-jest/src/jest.res.mjs";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";
import * as Graphology__Graph from "../src/Graphology__Graph.res.mjs";

Jest.describe("Layout - Circular", () => {
  let G = Graphology__Graph.MakeGraph({});
  Jest.test("generates circular layout positions", () => {
    let g = G.makeGraph(undefined);
    G.addNode(g, "A", undefined);
    G.addNode(g, "B", undefined);
    G.addNode(g, "C", undefined);
    G.addNode(g, "D", undefined);
    let positions = G.Layout.Circular.circular(g, undefined);
    let keys = Object.keys(positions);
    return Jest.Expect.toBe(Jest.Expect.expect(keys.length), 4);
  });
  Jest.test("assigns circular layout to graph", () => {
    let g = G.makeGraph(undefined);
    G.addNode(g, "A", undefined);
    G.addNode(g, "B", undefined);
    G.addNode(g, "C", undefined);
    G.Layout.Circular.assign(g, undefined);
    let hasX = G.hasNodeAttribute(g, "A", "x");
    let hasY = G.hasNodeAttribute(g, "A", "y");
    return Jest.Expect.toEqual(Jest.Expect.expect([
      hasX,
      hasY
    ]), [
      true,
      true
    ]);
  });
  Jest.test("respects layout options", () => {
    let g = G.makeGraph(undefined);
    G.addNode(g, "A", undefined);
    G.addNode(g, "B", undefined);
    G.Layout.Circular.assign(g, {
      center: 0.0,
      scale: 10.0
    });
    let xA = G.getNodeAttribute(g, "A", "x");
    let yA = G.getNodeAttribute(g, "A", "y");
    return Jest.Expect.toEqual(Jest.Expect.expect([
      xA !== undefined,
      yA !== undefined
    ]), [
      true,
      true
    ]);
  });
  Jest.test("handles single node", () => {
    let g = G.makeGraph(undefined);
    G.addNode(g, "A", undefined);
    let positions = G.Layout.Circular.circular(g, undefined);
    return Jest.Expect.toBe(Jest.Expect.expect(Object.keys(positions).length), 1);
  });
});

Jest.describe("Layout - CirclePack", () => {
  let G = Graphology__Graph.MakeGraph({});
  Jest.test("generates circle pack layout", () => {
    let g = G.makeGraph(undefined);
    G.addNode(g, "A", undefined);
    G.addNode(g, "B", undefined);
    G.addNode(g, "C", undefined);
    let positions = G.Layout.CirclePack.circlePack(g, undefined);
    let keys = Object.keys(positions);
    return Jest.Expect.toBe(Jest.Expect.expect(keys.length), 3);
  });
  Jest.test("assigns circle pack layout", () => {
    let g = G.makeGraph(undefined);
    G.addNode(g, "A", undefined);
    G.addNode(g, "B", undefined);
    G.Layout.CirclePack.assign(g, undefined);
    let hasX = G.hasNodeAttribute(g, "A", "x");
    let hasY = G.hasNodeAttribute(g, "A", "y");
    return Jest.Expect.toEqual(Jest.Expect.expect([
      hasX,
      hasY
    ]), [
      true,
      true
    ]);
  });
});

Jest.describe("Layout - Rotation", () => {
  let G = Graphology__Graph.MakeGraph({});
  Jest.test("rotates layout by angle", () => {
    let g = G.makeGraph(undefined);
    G.addNode(g, "A", {
      x: 1.0,
      y: 0.0
    });
    G.addNode(g, "B", {
      x: 0.0,
      y: 1.0
    });
    let originalX = G.getNodeAttribute(g, "A", "x");
    G.Layout.Rotation.assign(g, 3.14159 / 2.0, undefined);
    let newX = G.getNodeAttribute(g, "A", "x");
    return Jest.Expect.toBe(Jest.Expect.expect(Primitive_object.notequal(newX, originalX)), true);
  });
  Jest.test("handles zero rotation", () => {
    let g = G.makeGraph(undefined);
    G.addNode(g, "A", {
      x: 1.0,
      y: 0.0
    });
    let originalX = G.getNodeAttribute(g, "A", "x");
    let originalY = G.getNodeAttribute(g, "A", "y");
    G.Layout.Rotation.assign(g, 0.0, undefined);
    let newX = G.getNodeAttribute(g, "A", "x");
    let newY = G.getNodeAttribute(g, "A", "y");
    let xDiff = Math.abs(newX - originalX);
    let yDiff = Math.abs(newY - originalY);
    return Jest.Expect.toEqual(Jest.Expect.expect([
      xDiff < 0.0001,
      yDiff < 0.0001
    ]), [
      true,
      true
    ]);
  });
});

Jest.describe("Layout - Utils", () => {
  let G = Graphology__Graph.MakeGraph({});
  Jest.test("collects layout as dictionary", () => {
    let g = G.makeGraph(undefined);
    G.addNode(g, "A", {
      x: 1.0,
      y: 2.0
    });
    G.addNode(g, "B", {
      x: 3.0,
      y: 4.0
    });
    let layout = G.Layout.Utils.collectLayout(g, undefined);
    let posA = layout["A"];
    let posB = layout["B"];
    return Jest.Expect.toEqual(Jest.Expect.expect([
      posA,
      posB
    ]), [
      {
        x: 1.0,
        y: 2.0
      },
      {
        x: 3.0,
        y: 4.0
      }
    ]);
  });
  Jest.test("collects layout as flat array", () => {
    let g = G.makeGraph(undefined);
    G.addNode(g, "A", {
      x: 1.0,
      y: 2.0
    });
    G.addNode(g, "B", {
      x: 3.0,
      y: 4.0
    });
    let flatLayout = G.Layout.Utils.collectLayoutAsFlatArray(g, undefined);
    return Jest.Expect.toBe(Jest.Expect.expect(flatLayout.length), 4);
  });
  Jest.test("handles graph with missing coordinates", () => {
    let g = G.makeGraph(undefined);
    G.addNode(g, "A", undefined);
    G.addNode(g, "B", {
      x: 1.0,
      y: 2.0
    });
    let layout = G.Layout.Utils.collectLayout(g, undefined);
    return Jest.Expect.toBeGreaterThan(Jest.Expect.expect(Object.keys(layout).length), 0);
  });
});

Jest.describe("Layout - Integration", () => {
  let G = Graphology__Graph.MakeGraph({});
  Jest.test("can chain different layouts", () => {
    let g = G.makeGraph(undefined);
    G.addNode(g, "A", undefined);
    G.addNode(g, "B", undefined);
    G.addNode(g, "C", undefined);
    G.Layout.Circular.assign(g, undefined);
    G.Layout.Rotation.assign(g, 1.5708, undefined);
    let hasX = G.hasNodeAttribute(g, "A", "x");
    let hasY = G.hasNodeAttribute(g, "A", "y");
    return Jest.Expect.toEqual(Jest.Expect.expect([
      hasX,
      hasY
    ]), [
      true,
      true
    ]);
  });
  Jest.test("layout works with graph structure", () => {
    let g = G.makeGraph(undefined);
    G.addNode(g, "A", undefined);
    G.addNode(g, "B", undefined);
    G.addNode(g, "C", undefined);
    G.addEdge(g, "A", "B", undefined);
    G.addEdge(g, "B", "C", undefined);
    G.Layout.Circular.assign(g, undefined);
    let layout = G.Layout.Utils.collectLayout(g, undefined);
    return Jest.Expect.toBe(Jest.Expect.expect(Object.keys(layout).length), 3);
  });
});

/*  Not a pure module */
