// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/rescript-jest/src/jest.res.mjs";
import * as Graphology__Graph from "../src/Graphology__Graph.res.mjs";

Jest.describe("SimplePath - All Simple Paths", () => {
  let G = Graphology__Graph.MakeGraph({});
  let createTestGraph = () => {
    let g = G.makeGraph(undefined);
    G.addNode(g, "A", undefined);
    G.addNode(g, "B", undefined);
    G.addNode(g, "C", undefined);
    G.addNode(g, "D", undefined);
    G.addEdge(g, "A", "B", undefined);
    G.addEdge(g, "B", "D", undefined);
    G.addEdge(g, "A", "C", undefined);
    G.addEdge(g, "C", "D", undefined);
    G.addEdge(g, "B", "C", undefined);
    return g;
  };
  Jest.test("finds all simple paths between two nodes", () => {
    let g = createTestGraph();
    let paths = G.SimplePath.allSimplePaths(g, "A", "D", undefined, undefined);
    let numPaths = paths.length;
    let allStartWithA = paths.every(path => path[0] === "A");
    let allEndWithD = paths.every(path => path[path.length - 1 | 0] === "D");
    return Jest.Expect.toEqual(Jest.Expect.expect([
      numPaths > 1,
      allStartWithA,
      allEndWithD
    ]), [
      true,
      true,
      true
    ]);
  });
  Jest.test("handles direct connection", () => {
    let g = G.makeGraph(undefined);
    G.addNode(g, "A", undefined);
    G.addNode(g, "B", undefined);
    G.addEdge(g, "A", "B", undefined);
    let paths = G.SimplePath.allSimplePaths(g, "A", "B", undefined, undefined);
    let numPaths = paths.length;
    let firstPath = paths[0];
    return Jest.Expect.toEqual(Jest.Expect.expect([
      numPaths,
      firstPath
    ]), [
      1,
      [
        "A",
        "B"
      ]
    ]);
  });
  Jest.test("returns empty array for unreachable nodes", () => {
    let g = G.makeGraph(undefined);
    G.addNode(g, "A", undefined);
    G.addNode(g, "B", undefined);
    G.addNode(g, "C", undefined);
    G.addEdge(g, "A", "B", undefined);
    let paths = G.SimplePath.allSimplePaths(g, "A", "C", undefined, undefined);
    return Jest.Expect.toBe(Jest.Expect.expect(paths.length), 0);
  });
  Jest.test("handles graph with cycles", () => {
    let g = G.makeGraph(undefined);
    G.addNode(g, "A", undefined);
    G.addNode(g, "B", undefined);
    G.addNode(g, "C", undefined);
    G.addEdge(g, "A", "B", undefined);
    G.addEdge(g, "B", "C", undefined);
    G.addEdge(g, "C", "A", undefined);
    let paths = G.SimplePath.allSimplePaths(g, "A", "C", undefined, undefined);
    let hasPath = paths.length !== 0;
    let allSimple = paths.every(path => {
      let nodeSet = new Set(path);
      return nodeSet.size === path.length;
    });
    return Jest.Expect.toEqual(Jest.Expect.expect([
      hasPath,
      allSimple
    ]), [
      true,
      true
    ]);
  });
});

Jest.describe("SimplePath - All Simple Edge Paths", () => {
  let G = Graphology__Graph.MakeGraph({});
  Jest.test("finds all simple edge paths", () => {
    let g = G.makeGraph(undefined);
    G.addNode(g, "A", undefined);
    G.addNode(g, "B", undefined);
    G.addNode(g, "C", undefined);
    G.addEdgeWithKey(g, "e1", "A", "B", undefined);
    G.addEdgeWithKey(g, "e2", "B", "C", undefined);
    G.addEdgeWithKey(g, "e3", "A", "C", undefined);
    let edgePaths = G.SimplePath.allSimpleEdgePaths(g, "A", "C", undefined, undefined);
    return Jest.Expect.toBe(Jest.Expect.expect(edgePaths.length), 2);
  });
  Jest.test("edge paths correspond to node paths", () => {
    let g = G.makeGraph(undefined);
    G.addNode(g, "A", undefined);
    G.addNode(g, "B", undefined);
    G.addNode(g, "C", undefined);
    G.addEdgeWithKey(g, "e1", "A", "B", undefined);
    G.addEdgeWithKey(g, "e2", "B", "C", undefined);
    let edgePaths = G.SimplePath.allSimpleEdgePaths(g, "A", "C", undefined, undefined);
    let numPaths = edgePaths.length;
    let firstPath = edgePaths[0];
    return Jest.Expect.toEqual(Jest.Expect.expect([
      numPaths,
      firstPath
    ]), [
      1,
      [
        "e1",
        "e2"
      ]
    ]);
  });
});

Jest.describe("SimplePath - All Simple Edge Group Paths", () => {
  let G = Graphology__Graph.MakeGraph({});
  Jest.test("finds all simple edge group paths", () => {
    let g = G.makeGraph(undefined);
    G.addNode(g, "A", undefined);
    G.addNode(g, "B", undefined);
    G.addNode(g, "C", undefined);
    G.addEdgeWithKey(g, "e1", "A", "B", undefined);
    G.addEdgeWithKey(g, "e2", "B", "C", undefined);
    G.addEdgeWithKey(g, "e3", "A", "C", undefined);
    let edgeGroupPaths = G.SimplePath.allSimpleEdgeGroupPaths(g, "A", "C", undefined, undefined);
    return Jest.Expect.toBe(Jest.Expect.expect(edgeGroupPaths.length), 2);
  });
});

/*  Not a pure module */
