// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/rescript-jest/src/jest.res.mjs";
import * as Graphology__Graph from "../src/Graphology__Graph.res.mjs";

Jest.describe("SVG - Render to File", () => {
  let G = Graphology__Graph.MakeGraph({});
  Jest.test("renders graph to SVG file", () => {
    let g = G.makeGraph(undefined);
    G.addNode(g, "A", {
      x: 0.0,
      y: 0.0
    });
    G.addNode(g, "B", {
      x: 100.0,
      y: 0.0
    });
    G.addEdge(g, "A", "B", undefined);
    let rendered = {
      contents: false
    };
    G.SVG.render(g, "./test-graph.svg", undefined, () => {
      rendered.contents = true;
    });
    return Jest.Expect.toBe(Jest.Expect.expect(true), true);
  });
  Jest.test("renders with settings", () => {
    let g = G.makeGraph(undefined);
    G.addNode(g, "A", {
      x: 0.0,
      y: 0.0
    });
    let rendered = {
      contents: false
    };
    G.SVG.render(g, "./test-graph-with-settings.svg", {
      margin: 20,
      width: 800,
      height: 600
    }, () => {
      rendered.contents = true;
    });
    return Jest.Expect.toBe(Jest.Expect.expect(true), true);
  });
  Jest.test("renders empty graph", () => {
    let g = G.makeGraph(undefined);
    let rendered = {
      contents: false
    };
    G.SVG.render(g, "./test-empty-graph.svg", undefined, () => {
      rendered.contents = true;
    });
    return Jest.Expect.toBe(Jest.Expect.expect(true), true);
  });
});

Jest.describe("SVG - Integration with Layout", () => {
  let G = Graphology__Graph.MakeGraph({});
  Jest.test("renders graph after applying circular layout", () => {
    let g = G.makeGraph(undefined);
    G.addNode(g, "A", undefined);
    G.addNode(g, "B", undefined);
    G.addNode(g, "C", undefined);
    G.addEdge(g, "A", "B", undefined);
    G.addEdge(g, "B", "C", undefined);
    G.Layout.Circular.assign(g, undefined);
    let rendered = {
      contents: false
    };
    G.SVG.render(g, "./test-circular-layout.svg", undefined, () => {
      rendered.contents = true;
    });
    return Jest.Expect.toBe(Jest.Expect.expect(true), true);
  });
  Jest.test("complete workflow: graph -> layout -> SVG", () => {
    let g = G.makeGraph(undefined);
    G.addNode(g, "A", undefined);
    G.addNode(g, "B", undefined);
    G.addNode(g, "C", undefined);
    G.addNode(g, "D", undefined);
    G.addEdge(g, "A", "B", undefined);
    G.addEdge(g, "B", "C", undefined);
    G.addEdge(g, "C", "D", undefined);
    G.addEdge(g, "D", "A", undefined);
    G.Layout.Circular.assign(g, {
      center: 0.5,
      scale: 100.0
    });
    let rendered = {
      contents: false
    };
    G.SVG.render(g, "./test-workflow.svg", {
      margin: 50,
      width: 800,
      height: 800
    }, () => {
      rendered.contents = true;
    });
    return Jest.Expect.toBe(Jest.Expect.expect(true), true);
  });
});

/*  Not a pure module */
